apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demo-autoscaler
  namespace: litmus
  annotations:
    description: |
      Injects pod-autoscaler chaos in a Kubernetes resource to scale up or down the application pods, testing its resilience
      and the node autoscaling capabilities of the cluster.
spec:
  entrypoint: pod-autoscaler
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
      - name: category
        value: kubernetes
      - name: context
        value: pod-autoscaler
      - name: hubPath
        value: /tmp/chaos-charts
  serviceAccountName: argo-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  templates:
    - name: pod-autoscaler
      steps:
        - - name: install-chaos-faults
            template: install-chaos-faults
            arguments: {}
        - - name: run-chaos-experiment
            template: run-chaos-experiment
            arguments: {}
        - - name: cleanup-chaos-resources
            template: cleanup-chaos-resources
            arguments: {}
    - name: install-chaos-faults
      inputs:
        artifacts:
          - name: install-chaos-faults
            path: "{{workflow.parameters.hubPath}}"
            git:
              repo: "https://github.com/litmuschaos/chaos-charts.git"
              revision: "master"
              depth: 1
      container:
        name: install-chaos-faults
        image: litmuschaos/k8s:3.24.0
        command:
          - sh
          - -c
        args:
          - kubectl apply --wait -f {{workflow.parameters.hubPath}}/faults/{{workflow.parameters.category}}/{{workflow.parameters.context}}/fault.yaml -n {{workflow.parameters.adminModeNamespace}}
    - name: run-chaos-experiment
      inputs:
        artifacts:
          - name: run-chaos-experiment
            path: /tmp/chaosengine-{{workflow.parameters.context}}.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  # Use generateName to create a unique name for each experiment run, appending the experiment ID for traceability
                  generateName: "{{workflow.parameters.context}}-"
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    workflow_run_id: "{{workflow.uid}}"
                    context: "{{workflow.parameters.context}}"
                spec:
                  engineState: "active"
                  auxiliaryAppInfo: ""
                  appinfo:
                    appkind: "deployment"
                    appns: "litmus-demo"
                    applabel: "app.kubernetes.io/name=podtato-head"
                  chaosServiceAccount: litmus-admin
                  experiments:
                    # The Chaos Experiment to run
                    # The name of the experiment is set based on workflow parameters, and should match the name in the ChaosExperiment manifest installed by the previous step
                    - name: "{{workflow.parameters.context}}"
                      spec:
                        components:
                          env:
                          - name: TOTAL_CHAOS_DURATION
                            value: "60"
                          - name: RAMP_TIME
                            value: ""
                          - name: REPLICA_COUNT
                            value: "2"
                          - name: DEFAULT_HEALTH_CHECK
                            value: "false"
                        probe:
                          - name: "podtato-head-demo-url"
                            type: "httpProbe"
                            httpProbe/inputs:
                              url: "https://podtato-head-demo.playground-a.us-east-1.kic-dev.shuttercloud.org"
                              insecureSkipVerify: false
                              method:
                                get:
                                  criteria: "=="
                                  responseCode: "200"
                            mode: "Continuous"
                            runProperties:
                              probeTimeout: 5s
                              interval: 5s
                              retry: 1
                              probePollingInterval: 2s
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: run-chaos
        image: litmuschaos/litmus-checker:3.24.0
        args:
          - -file=/tmp/chaosengine-{{workflow.parameters.context}}.yaml
          - -saveName=/tmp/engine-name
    - name: cleanup-chaos-resources
      container:
        name: cleanup-chaos-resources
        image: litmuschaos/k8s:3.24.0
        command:
          - sh
          - -c
        args:
          - kubectl delete chaosengine -l "workflow_run_id={{workflow.uid}}" -n {{workflow.parameters.adminModeNamespace}}